# Prometheus configuration for monitoring roachprod-centralized

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # Add alerting rules here if needed
  # - "alerts.yml"

scrape_configs:
  # roachprod-centralized metrics
  - job_name: 'roachprod-centralized'
    static_configs:
      - targets: ['roachprod-centralized:8081']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # CockroachDB metrics
  - job_name: 'cockroachdb'
    static_configs:
      - targets: ['cockroachdb:8080']
    metrics_path: '/_status/vars'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# Optional: Add alerting configuration
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093