// Copyright 2025 The Cockroach Authors.
//
// Use of this software is governed by the CockroachDB Software License
// included in the /LICENSE file.

// Code generated by mockery v2.53.4. DO NOT EDIT.

package clustersrepmock

import (
	context "context"

	clusters "github.com/cockroachdb/cockroach/pkg/cmd/roachprod-centralized/repositories/clusters"

	logger "github.com/cockroachdb/cockroach/pkg/cmd/roachprod-centralized/utils/logger"

	mock "github.com/stretchr/testify/mock"

	filtertypes "github.com/cockroachdb/cockroach/pkg/cmd/roachprod-centralized/utils/filters/types"

	cloudcluster "github.com/cockroachdb/cockroach/pkg/roachprod/cloud/types"
)

// IClustersRepository is an autogenerated mock type for the IClustersRepository type
type IClustersRepository struct {
	mock.Mock
}

// AcquireSyncLock provides a mock function with given fields: ctx, l, instanceID
func (_m *IClustersRepository) AcquireSyncLock(ctx context.Context, l *logger.Logger, instanceID string) (bool, error) {
	ret := _m.Called(ctx, l, instanceID)

	if len(ret) == 0 {
		panic("no return value specified for AcquireSyncLock")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *logger.Logger, string) (bool, error)); ok {
		return rf(ctx, l, instanceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *logger.Logger, string) bool); ok {
		r0 = rf(ctx, l, instanceID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *logger.Logger, string) error); ok {
		r1 = rf(ctx, l, instanceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClearPendingOperations provides a mock function with given fields: ctx, l
func (_m *IClustersRepository) ClearPendingOperations(ctx context.Context, l *logger.Logger) error {
	ret := _m.Called(ctx, l)

	if len(ret) == 0 {
		panic("no return value specified for ClearPendingOperations")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *logger.Logger) error); ok {
		r0 = rf(ctx, l)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConditionalEnqueueOperation provides a mock function with given fields: ctx, l, operation
func (_m *IClustersRepository) ConditionalEnqueueOperation(ctx context.Context, l *logger.Logger, operation clusters.OperationData) (bool, error) {
	ret := _m.Called(ctx, l, operation)

	if len(ret) == 0 {
		panic("no return value specified for ConditionalEnqueueOperation")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *logger.Logger, clusters.OperationData) (bool, error)); ok {
		return rf(ctx, l, operation)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *logger.Logger, clusters.OperationData) bool); ok {
		r0 = rf(ctx, l, operation)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *logger.Logger, clusters.OperationData) error); ok {
		r1 = rf(ctx, l, operation)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCluster provides a mock function with given fields: ctx, l, cluster
func (_m *IClustersRepository) DeleteCluster(ctx context.Context, l *logger.Logger, cluster cloudcluster.Cluster) error {
	ret := _m.Called(ctx, l, cluster)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCluster")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *logger.Logger, cloudcluster.Cluster) error); ok {
		r0 = rf(ctx, l, cluster)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EnqueueOperation provides a mock function with given fields: ctx, l, operation
func (_m *IClustersRepository) EnqueueOperation(ctx context.Context, l *logger.Logger, operation clusters.OperationData) error {
	ret := _m.Called(ctx, l, operation)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueOperation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *logger.Logger, clusters.OperationData) error); ok {
		r0 = rf(ctx, l, operation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCluster provides a mock function with given fields: ctx, l, name
func (_m *IClustersRepository) GetCluster(ctx context.Context, l *logger.Logger, name string) (cloudcluster.Cluster, error) {
	ret := _m.Called(ctx, l, name)

	if len(ret) == 0 {
		panic("no return value specified for GetCluster")
	}

	var r0 cloudcluster.Cluster
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *logger.Logger, string) (cloudcluster.Cluster, error)); ok {
		return rf(ctx, l, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *logger.Logger, string) cloudcluster.Cluster); ok {
		r0 = rf(ctx, l, name)
	} else {
		r0 = ret.Get(0).(cloudcluster.Cluster)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *logger.Logger, string) error); ok {
		r1 = rf(ctx, l, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetClusters provides a mock function with given fields: ctx, l, filters
func (_m *IClustersRepository) GetClusters(ctx context.Context, l *logger.Logger, filters filtertypes.FilterSet) (cloudcluster.Clusters, error) {
	ret := _m.Called(ctx, l, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetClusters")
	}

	var r0 cloudcluster.Clusters
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *logger.Logger, filtertypes.FilterSet) (cloudcluster.Clusters, error)); ok {
		return rf(ctx, l, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *logger.Logger, filtertypes.FilterSet) cloudcluster.Clusters); ok {
		r0 = rf(ctx, l, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cloudcluster.Clusters)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *logger.Logger, filtertypes.FilterSet) error); ok {
		r1 = rf(ctx, l, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPendingOperations provides a mock function with given fields: ctx, l
func (_m *IClustersRepository) GetPendingOperations(ctx context.Context, l *logger.Logger) ([]clusters.OperationData, error) {
	ret := _m.Called(ctx, l)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingOperations")
	}

	var r0 []clusters.OperationData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *logger.Logger) ([]clusters.OperationData, error)); ok {
		return rf(ctx, l)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *logger.Logger) []clusters.OperationData); ok {
		r0 = rf(ctx, l)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]clusters.OperationData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *logger.Logger) error); ok {
		r1 = rf(ctx, l)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSyncStatus provides a mock function with given fields: ctx, l
func (_m *IClustersRepository) GetSyncStatus(ctx context.Context, l *logger.Logger) (*clusters.SyncStatus, error) {
	ret := _m.Called(ctx, l)

	if len(ret) == 0 {
		panic("no return value specified for GetSyncStatus")
	}

	var r0 *clusters.SyncStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *logger.Logger) (*clusters.SyncStatus, error)); ok {
		return rf(ctx, l)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *logger.Logger) *clusters.SyncStatus); ok {
		r0 = rf(ctx, l)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clusters.SyncStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *logger.Logger) error); ok {
		r1 = rf(ctx, l)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReleaseSyncLock provides a mock function with given fields: ctx, l, instanceID
func (_m *IClustersRepository) ReleaseSyncLock(ctx context.Context, l *logger.Logger, instanceID string) error {
	ret := _m.Called(ctx, l, instanceID)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseSyncLock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *logger.Logger, string) error); ok {
		r0 = rf(ctx, l, instanceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StoreCluster provides a mock function with given fields: ctx, l, cluster
func (_m *IClustersRepository) StoreCluster(ctx context.Context, l *logger.Logger, cluster cloudcluster.Cluster) error {
	ret := _m.Called(ctx, l, cluster)

	if len(ret) == 0 {
		panic("no return value specified for StoreCluster")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *logger.Logger, cloudcluster.Cluster) error); ok {
		r0 = rf(ctx, l, cluster)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StoreClusters provides a mock function with given fields: ctx, l, _a2
func (_m *IClustersRepository) StoreClusters(ctx context.Context, l *logger.Logger, _a2 cloudcluster.Clusters) error {
	ret := _m.Called(ctx, l, _a2)

	if len(ret) == 0 {
		panic("no return value specified for StoreClusters")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *logger.Logger, cloudcluster.Clusters) error); ok {
		r0 = rf(ctx, l, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIClustersRepository creates a new instance of IClustersRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIClustersRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IClustersRepository {
	mock := &IClustersRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
